version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /
    command: uvicorn pypi_scout.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
