name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: pypiscoutacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Backend Docker image
        run: |
          docker build -t pypi-scout-backend .

      - name: Push Backend Docker image to Azure Container Registry
        run: |
          docker tag pypi-scout-backend pypiscoutacr.azurecr.io/pypi-scout-backend:latest
          docker push pypiscoutacr.azurecr.io/pypi-scout-backend:latest

      - name: Build Frontend Docker image
        run: |
          docker build -t pypi-scout-frontend -f frontend/Dockerfile ./frontend

      - name: Push Frontend Docker image to Azure Container Registry
        run: |
          docker tag pypi-scout-frontend pypiscoutacr.azurecr.io/pypi-scout-frontend:latest
          docker push pypiscoutacr.azurecr.io/pypi-scout-frontend:latest
